export const initialStateTasks = [
    {
        taskId: 'FC–7',
        status: 'todo',
        priority: 'major',
        storyPoints: 2,
        title: 'Сделать более заметными поля "Название интервью" и "Респондент"',
        content: 'Сейчас многие пользователи жалуются на незаметные поля "Название интервью" и "Респондент" на первом экране при добавлении интервью. Нужен макет с более заметными полями',
    },
    {
        taskId: 'BC–14',
        status: 'todo',
        priority: 'undefined',
        storyPoints: 1,
        title: 'As a user, I want to see actual overusage price for next download',
        content: 'DESCRIPTION: As a user, I want to see actual overusage price for next download',
    },
    {
        taskId: 'MAR–14',
        status: 'in_progress',
        priority: 'normal',
        storyPoints: 3,
        title: 'As an external contributor, I want to be able to see status of uploaded materials',
        content: 'DESCRIPTION: As an external contributor, I want to be able to see status of uploaded materials',
    },
    {
        taskId: 'FC–19',
        status: 'in_progress',
        priority: 'critical',
        storyPoints: 3,
        title: 'Replace JustComments with something',
        content: 'DESCRIPTION: Replace JustComments with something',
    },
    {
        taskId: 'FC–13',
        status: 'test',
        priority: 'minor',
        storyPoints: 1,
        title: 'As a user, I want to access Intercom help center, so that I am not confused by Crisp',
        content: 'DESCRIPTION: As a user, I want to access Intercom help center, so that I am not confused by Crisp',
    },
    {
        taskId: 'FC–17',
        status: 'test',
        priority: 'critical',
        storyPoints: 2,
        title: 'Remove requests to ipfy service from frontend',
        content: 'DESCRIPTION: Remove requests to ipfy service from frontend',
    },
    {
        taskId: 'FC–8',
        status: 'done',
        priority: 'major',
        storyPoints: 5,
        title: 'Interate nuxt-18n in product-developers project',
        content: 'DESCRIPTION: Interate nuxt-18n in product-developers project',
    },
    {
        taskId: 'MAR–18',
        status: 'done',
        priority: 'normal',
        storyPoints: 2,
        title: 'CLONE – As an external contributor, I want to be able to upload a zip of my original materials',
        content: 'DESCRIPTION: CLONE – As an external contributor, I want to be able to upload a zip of my original materials',
    },
]